apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami/
    targetRevision: 4.4.9
    chart: rabbitmq-cluster-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true