apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-kustomize
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AkulovNV/otus-ol-gitops-argo.git
    path: applications/app-kustomize/app
    targetRevision: main
    plugin:
      name: avp-helm-kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true