apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-2
  namespace: app-2
spec:
  project: default
  source:
    repoURL: https://github.com/AkulovNV/otus-ol-gitops-argo.git
    path: applications/app/resources
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true